return {
	-- R6
	{
		Part0 = "HumanoidRootPart",
		Part1 = "Torso",
		Type = 1,
		RPart0 = "ROOT",
		RPart1 = "Torso",
	},
	{
		Part0 = "Torso",
		Part1 = "Head",
		Type = 1,
		RPart0 = "Torso",
		RPart1 = "Head",
	},
	{
		Part0 = "Torso",
		Part1 = "Left Arm",
		Type = 1,
		RPart0 = "Torso",
		RPart1 = "Left Arm",
	},
	{
		Part0 = "Torso",
		Part1 = "Right Arm",
		Type = 1,
		RPart0 = "Torso",
		RPart1 = "Right Arm",
	},
	{
		Part0 = "Torso",
		Part1 = "Left Leg",
		Type = 1,
		RPart0 = "Torso",
		RPart1 = "Left Leg",
	},
	{
		Part0 = "Torso",
		Part1 = "Right Leg",
		Type = 1,
		RPart0 = "Torso",
		RPart1 = "Right Leg",
	},
	-- R15
	{
		Part0 = "HumanoidRootPart",
		Part1 = "LowerTorso",
		Type = 2,
		RPart0 = "ROOT",
		RPart1 = "Torso",
		C0 = Vector3.new(0, 0, 0),
		C1 = Vector3.new(0, 0, 0),
	},
	{
		Part0 = "UpperTorso",
		Part1 = "Head",
		Type = 2,
		RPart0 = "Torso",
		RPart1 = "Head",
		C0 = Vector3.new(0, 1, 0),
		C1 = Vector3.new(0, -0.5, 0),
	},
	{
		Part0 = "UpperTorso",
		Part1 = "LeftUpperArm",
		Type = 2,
		RPart0 = "Torso",
		RPart1 = "Left Arm",
		C0 = Vector3.new(-1, 0.5, 0),
		C1 = Vector3.new(0.5, 0.5, 0),
	},
	{
		Part0 = "UpperTorso",
		Part1 = "RightUpperArm",
		Type = 2,
		RPart0 = "Torso",
		RPart1 = "Right Arm",
		C0 = Vector3.new(1, 0.5, 0),
		C1 = Vector3.new(-0.5, 0.5, 0),
	},
	{
		Part0 = "LowerTorso",
		Part1 = "LeftUpperLeg",
		Type = 2,
		RPart0 = "Torso",
		RPart1 = "Left Leg",
		C0 = Vector3.new(-0.5, -1, 0),
		C1 = Vector3.new(0, 1, 0),
	},
	{
		Part0 = "LowerTorso",
		Part1 = "RightUpperLeg",
		Type = 2,
		RPart0 = "Torso",
		RPart1 = "Right Leg",
		C0 = Vector3.new(0.5, -1, 0),
		C1 = Vector3.new(0, 1, 0),
	},
}